const Head = () => {
  return (
    <>
      {/* <title>BookIt </title> */}
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* TODO: replace favicon.ico to custom */}
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Head;
